#!/usr/bin/env Rscript
#
# Runs a general linear model (GLM) analysis of region-based brain morphometry data.
# The data have typically been generated by FreeSurfer.
#
# Written by Tim Schäfer, 202-01-22

library("brainnet");
library("fsbrain");   # loading neuroimaging data and visualizing results. you need a version > 0.5.0, to get that run: devtools::install_github("dfsp-spirit/fsbrain")
library("readxl");    # read Excel demographcis file
library("MatchIt");   # matching of patient/control groups
library("ggplot2");   # general purpose plots
library("slmtools");  # internal R package of Ecker neuroimaging group for mass-univariate GLM analysis.

################################################################################
########################## Load data and demographics ##########################
################################################################################

do_plot=FALSE;
measure = "thickness";

if(brainnet:::get_os() == "linux") {
    study_dir = "~/nas/projects/abide";
    if(! dir.exists(study_dir)) {
        study_dir = sprintf("/media/%s/science/data/abide", Sys.getenv("LOGNAME"));
    }
} else {
    study_dir = "/Volumes/shared/projects/abide";
}

if(dir.exists("~/data/abide_min")) {
    study_dir = "~/data/abide_min"; # use local minimal data dir if available, loading from a local SSD is much faster than loading via LAN from the NAS.
}

subjects_dir = file.path(study_dir, "structural"); # the FreeSurfer SUBJECTS_DIR containing the neuroimaging data.
if(! dir.exists(subjects_dir)) {
    stop(sprintf("The subjects_dir '%s' does not exist.\n", subjects_dir));
}

demographics_file = system.file("extdata", "ABIDE_Phenotypic_V1_0b_preprocessed1.csv", package = "brainnet", mustWork = TRUE);
demographics = readxl::read_excel(demographics_file);
